"""Ajustando nome da tabela para TODO List

Revision ID: 3ba0259a5965
Revises: 73d7611a758e
Create Date: 2025-07-01 00:41:48.292578

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ba0259a5965'
down_revision: Union[str, None] = '73d7611a758e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
