"""Altera campo description

Revision ID: 421e970e1b56
Revises: e8f7add0cff4
Create Date: 2025-10-12 00:14:52.227643

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '421e970e1b56'
down_revision: Union[str, None] = 'e8f7add0cff4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('DoUp', 'description',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('DoUp', 'description',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
