"""Create Relationship Between ToDo_List and ToDo_Client

Revision ID: 3b4cf7eb64af
Revises: 2624e103a143
Create Date: 2024-09-20 04:26:15.332276

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b4cf7eb64af'
down_revision: Union[str, None] = '2624e103a143'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ToDo_List', 'task_client_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ToDo_List', 'task_client_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
