"""Create Table of Task Client

Revision ID: 8ca5f5e5bacc
Revises: fa4778dc274f
Create Date: 2024-09-14 03:36:21.330876

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ca5f5e5bacc'
down_revision: Union[str, None] = 'fa4778dc274f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'ToDo_List_Client',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('title', sa.String(length=255), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('ToDo_List', 'created',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ToDo_List', 'created',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=False)
    op.drop_table('ToDo_List_Client')
    # ### end Alembic commands ###
