"""Create Relationship Create Relationship between todo_list client and todo_list model

Revision ID: 90539f34548b
Revises: 8ca5f5e5bacc
Create Date: 2024-09-14 04:15:36.926098

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90539f34548b'
down_revision: Union[str, None] = '8ca5f5e5bacc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ToDo_List', sa.Column('task_client_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'ToDo_List', 'ToDo_List_Client', ['task_client_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ToDo_List', type_='foreignkey')
    op.drop_column('ToDo_List', 'task_client_id')
    # ### end Alembic commands ###
