"""Create Relationship between ToDoList and ToDoClient

Revision ID: a77d010dc7d7
Revises: 7756c0ed72d8
Create Date: 2024-09-27 03:28:21.473968

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a77d010dc7d7'
down_revision: Union[str, None] = '7756c0ed72d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
