"""create_relationship_between_todolist

Revision ID: ac7a4850baa8
Revises: c32f0aa533ae
Create Date: 2024-11-06 03:31:48.438181

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac7a4850baa8'
down_revision: Union[str, None] = 'c32f0aa533ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
