"""create table todoclient

Revision ID: c32f0aa533ae
Revises: 71700e3bb108
Create Date: 2024-11-06 03:23:57.798536

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c32f0aa533ae'
down_revision: Union[str, None] = '71700e3bb108'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ToDo_Client',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('ToDo_List', sa.Column('task_client_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'ToDo_List', 'ToDo_Client', ['task_client_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ToDo_List', type_='foreignkey')
    op.drop_column('ToDo_List', 'task_client_id')
    op.drop_table('ToDo_Client')
    # ### end Alembic commands ###
